# web server
nginx:
  image: nginx:latest
  ports:
    - "8181:80"
    - "4431:443"
  volumes:
    # app
    - ./app/src:/usr/share/nginx/html
    # nginx configs
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    - ./nginx/conf.d/:/etc/nginx/conf.d/:ro
  links:
    - fpm:__DOCKER_PHP_FPM__

# php-fpm
fpm:
  build: ./php-fpm
  ports:
    - "9000"
  volumes:
    - ./app/src:/usr/share/nginx/html
    # Your php.ini
    - ./php-fpm/php.ini-production:/usr/local/etc/php/php.ini:ro
  links:
    - redis:redis
redis:
  image: redis:3
  ports: 
    - "8379:6379"
  environment:
    - ALLOW_EMPTY_PASSWORD=yes
  volumes:
    - ./data/redis-persistence:/bitnami